 # Most useful (5) Numpy Operations for beginners! 


### These are the 5 Numpy Operations which you need to know, if you're a beginner. 

NumPy (Numerical Python) is an open-source core Python library for scientific computations. It is a general-purpose array and matrices processing package.
The below are the list of functions which will be discussed in detail:

- sort() 
- count_nonzero() 
- argmax() 
- linalg.eig()
- diag() 

In [38]:
!pip install jovian --upgrade --quiet 

In [39]:
import jovian

In [ ]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [41]:
import numpy as np

In [42]:
#List of functions explained 
function1 = "np.sort()"
function2 = "np.count_nonzero()"
function3 = "np.argmax()"
function4 = "np.linalg.eig()"
function5 = "np.diag()"

## Function 1 - np.sort 

Sorting function (np.sort) in Numpy is used to sort the elements present in an array in ascending order. 

In [43]:
# Example 1 - working model
arr1 = [[5, 3, 0, - 1], 
        [8, 4, 9, 3]]

arr2 = [[57, 46, 73], 
        [78, 99, 110]]

print (np.sort(arr1, axis = -1)) 
print (np.sort(arr1))
print (np.sort(arr2)) 

[[-1  0  3  5]
 [ 3  4  8  9]]
[[-1  0  3  5]
 [ 3  4  8  9]]
[[ 46  57  73]
 [ 78  99 110]]


We assigned values to 2 arrays (2D) named arr1 and arr2. We used sort function in Numpy package to sort the elements present in an array. When we haven't mentioned anything in the axis argument, it takes the last axis by default (axis = - 1). 

In [44]:
# Example 2 - working model
arr3 = [[-5, 13], 
        [8, -4]]

arr4 = [[57, -46, 73], 
        [-78, 99, -110],
        [0,3,5]]

print (np.sort(arr3, axis = None)) 
print (np.sort(arr4, axis = 0))

[-5 -4  8 13]
[[ -78  -46 -110]
 [   0    3    5]
 [  57   99   73]]


We assigned values to 2 arrays (2D) named arr3 and arr4. We used sort function in Numpy package to sort the elements present in an array. When we haven't mentioned anything in the axis argument, it takes the last axis by default (axis = - 1). Here, we mentioned axis = None, so it will sort the entire elements present in array and display it as a flattened array. When axis =0,it will sort the elements along the axis = 0.

In [46]:
# Example 3 - breaking model
arr1 = [[5, 3], [8, 4]] 
arr2 = [[57, 46, 73], [78, 99, 110]] 
print (np.sort(arr1, axis = 2)) 

AxisError: axis 2 is out of bounds for array of dimension 2

In the above example, we assigned a value to the axis argument (axis =2), that's is not applicable to this array(2D). so it's an error. we can avoid this error by mentioning correct values in axis argument

In general, we can use this sort function to sort the elements present in an array in ascending order. For now, we don't have any option in sort function to sort the elements in descending order.

In [47]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "lafirm/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/lafirm/numpy-array-operations


'https://jovian.ai/lafirm/numpy-array-operations'

## Function 2 - np.count_nonzero()

np.count_nonzero() in Numpy package is used to count the number of non zero elements present in the given array

In [49]:
# Example 1 - working model
array1 = np.arange(9).reshape(3,3)
print (array1)
print ("The number of non zero values present in the given array is {}".format(np.count_nonzero(array1))) 

[[0 1 2]
 [3 4 5]
 [6 7 8]]
The number of non zero values present in the given array is 8


In the above example, we used simple np.count_nonzero() function without any arguments to count the the non zeros elements

In [50]:
# Example 2 - working model 
array2 = ([13,4,0,13], 
          [5,7,4,0], 
          [9,5,7,5])
array2 = np.array(array2)
print ("The number of non zero values present in the given array is {}".format(np.count_nonzero(array2))) 
print ("The number of non zero values present in the given array is {} along the axis '0'".format(np.count_nonzero(array2,axis = 0, keepdims = True ))) 
print ("The number of non zero values present in the given array is {} along the axis '1'".format(np.count_nonzero(array2, axis = 1, keepdims = False ))) 

The number of non zero values present in the given array is 10
The number of non zero values present in the given array is [[3 3 2 2]] along the axis '0'
The number of non zero values present in the given array is [3 3 4] along the axis '1'


In the above example, we assigned values to axis argument in the np.count_nonzero()  function to count the number of non zero values present in the given array along a particular axis (axis =0 and axis =1), when we set keepdims argument as True, the axes that are counted are displayed in
the result as dimensions with size one.

In [51]:
# Example 3 - breaking model 
array3 = np.zeros((3,3), dtype =int ) 
print ("The number of non zero values present in the given array is {}".format(np.count_nonzero(array3, axis = 0 , True)))

SyntaxError: positional argument follows keyword argument (1373368298.py, line 3)

In the above example, we haven't mentioned the keyword for the last argument keepdims, since its an keyword only argument, it throws an error.
We can simply avoid this error mentioning the keyword name. 

In general, we can use this np.count_nonzero() function without any arguments except an array to count the number of non zero values present in the given array. If you want to count the number of non zero values along a particular axis, you have to use axis argument and you can use use keepdims argument to display the results as 1D Array. 

In [52]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "lafirm/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/lafirm/numpy-array-operations


'https://jovian.ai/lafirm/numpy-array-operations'

## Function 3 - np.argmax()

np.argmax () in Numpy package is used to find the indices of the maximum values along a particular axis.


In [54]:
# Example 1 - working model 
print (array1)
print ("The index of the max value in the given array is {}". format (np.argmax(array1)) ) 

[[0 1 2]
 [3 4 5]
 [6 7 8]]
The index of the max value in the given array is 8


In the above example, we used simple np.argmax() function without any arguments to find the indices of the max values in the given array

In [56]:
# Example 2 - working model
arr = np.zeros((4, ), dtype = int) #an array to store the output 
print ("The output array before storing the argmax results is {} ". format(arr)) 
print ("The array where we want to find the indices of max values is {}". format (array2)) 
print ("The indices of the max values in the given array along axis '0' is {}". format (np.argmax(array2,axis =0, out = arr) )) 
print ("The output array after storing the argmax results is {} ". format(arr)) 

The output array before storing the argmax results is [0 0 0 0] 
The array where we want to find the indices of max values is [[13  4  0 13]
 [ 5  7  4  0]
 [ 9  5  7  5]]
The indices of the max values in the given array along axis '0' is [0 1 2 0]
The output array after storing the argmax results is [0 1 2 0] 


In the above example, we used np.argmax() function with axis arguments to find the indices of the max values in the given array along a particular axis and we can store the output in another array with the argument 'out'.

In [58]:
# Example 3 - breaking model 
arr = np.zeros((4, ), dtype = float) #an array to store the output 
print ("The output array before storing the argmax results is {} ". format(arr)) 
print ("The array where we want to find the indices of max values is {}". format (array2)) 
print ("The indices of the max values in the given array along axis '0' is {}". format (np.argmax(array2,axis =0, out = arr) )) 
print ("The output array after storing the argmax results is {} ". format(arr)) 

The output array before storing the argmax results is [0. 0. 0. 0.] 
The array where we want to find the indices of max values is [[13  4  0 13]
 [ 5  7  4  0]
 [ 9  5  7  5]]


TypeError: Cannot cast array data from dtype('float64') to dtype('int64') according to the rule 'safe'

In the above example, we tried to store the argmax results in an array having same dimensions but different data types.
Hence it throws an error.  We can avoid this error by storing the result output in an array having same dimensions and same data types. 

In general, np.argmax() function is to find the indices of the max values in the given array. 

In case of multiple occurrences of the maximum values, the indices
corresponding to the first occurrence will be returned. 

In [59]:
jovian.commit ()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "lafirm/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/lafirm/numpy-array-operations


'https://jovian.ai/lafirm/numpy-array-operations'

## Function 4 - np.linalg.eig()

np.linalg.eig() function is used to find the eigenvalues and right eigenvectors of a square matrix

In [62]:
# Example 1 - working model
evalue, evector = np.linalg.eig (np.array([[3,4,-2], 
             [1,4,-1],
             [2,6,-1]]) ) 
print ("The eigenvalues of the given square matrix is {} ". format (evalue)) 
print ("*******")
print ("*******")
print ("The eigenvectors of the given square matrix is \n{} ". format (evector)) 

The eigenvalues of the given square matrix is [3. 2. 1.] 
*******
*******
The eigenvectors of the given square matrix is 
[[-4.08248290e-01  2.63507484e-15  7.07106781e-01]
 [-4.08248290e-01  4.47213595e-01 -8.32667268e-17]
 [-8.16496581e-01  8.94427191e-01  7.07106781e-01]] 


In the above example, we used simple np.linalg.eig() function to find the eigenvalues and eigenvectors of the given square matrix. It returns both eigenvalues and eigenvectors combined as one output. 

In [63]:
# Example 2 - working model 
evalue, evector = np.linalg.eig (np.array([[3,4], 
             [1,1]] )) 
print ("The eigenvalues of the given square matrix is {} ". format (evalue)) 
print ("*******")
print ("*******")
print ("The eigenvectors of the given square matrix is \n{} ". format (evector))  

The eigenvalues of the given square matrix is [ 4.23606798 -0.23606798] 
*******
*******
The eigenvectors of the given square matrix is 
[[ 0.95542256 -0.77743752]
 [ 0.29524181  0.62896017]] 


In the above example, we used simple np.linalg.eig() function to find the eigenvalues and eigenvectors of the given square matrix. It returns both eigenvalues and eigenvectors combined as one output. We stored the 2 values in two separate variables to display it clearly in output

In [64]:
# Example 3 - breaking model 
evalue, evector = np.linalg.eig (np.array([[3,4,-2,4], 
             [1,4,-1, 5],
             [2,6,-1,6]]) ) 
print ("The eigenvalues of the given square matrix is {} ". format (evalue)) 
print ("*******")
print ("*******")
print ("The eigenvectors of the given square matrix is \n{} ". format (evector)) 

LinAlgError: Last 2 dimensions of the array must be square

In the above example, we tried to find the eigenvalues and eigenvectors of an array with shape (3,4). Hence it throws an error. Since this function np.linalg.eig() can work only with the square matrix. We can avoid this error by using square matrix.

In general, np.linalg.eig() function is to find the eigenvalues and right eigenvectors of a given square matrix. If needed, we can use the np.linalg.eigvals() to find the eigenvalues of a general matrix

In [65]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "lafirm/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/lafirm/numpy-array-operations


'https://jovian.ai/lafirm/numpy-array-operations'

## Function 5 - np.diag() 

np.diag() function in Numpy package is used to extract the diagonal value of an array along a particular axis or create a diagonal array with the given elements. 

In [66]:
# Example 1 - working model 
a = np.diag(array2, k=0)
b = np.diag(array2, k=1)
print (array2)
print ("*******")
print ("*******")
print (a)
print (b)

[[13  4  0 13]
 [ 5  7  4  0]
 [ 9  5  7  5]]
*******
*******
[13  7  7]
[4 4 5]


In the above example, we found the diagonal value of an existing array "array2" along kth axis and k+1 axis

In [67]:
# Example 2 - working model 
np.diag([3,4,0,3])

array([[3, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 3]])

In the above example, we constructed a diagonal matrix (array) using the np.diag() function along the kth axis. By default, it assumes k=0 if not mentioned. 

In [68]:
# Example 3 - breaking model 
np.diag(4, )

ValueError: Input must be 1- or 2-d.

In the above example, we tried to construct a diagonal array with a single element. But we failed to pass the value as an array (1D or 2D), hence it throws an error. we can simply avoid this error by passing the value ad given below

np.diag([4, ])

In general, we use np.diag() to extract the diagonal value or construct a diagonal array. If you want to get the sum along the diagonals, you can use trace() function and use triu(), tril()  function to find the upper triangle and lower triangle. 

In [69]:
jovian.commit() 

<IPython.core.display.Javascript object>

[jovian] Updating notebook "lafirm/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/lafirm/numpy-array-operations


'https://jovian.ai/lafirm/numpy-array-operations'

## Conclusion

We have successfully discussed the 5 basic operations along with working and breaking examples in Numpy package which you need to know before going deeper. Also please check out the reference links given below to know more about the other Numpy Operations. 

## Reference Links

* Numpy official tutorial: 
https://numpy.org/doc/stable/user/quickstart.html

* Numpy array Operations: https://www.geeksforgeeks.org/python-operations-on-numpy-arrays/ 

In [70]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "lafirm/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/lafirm/numpy-array-operations


'https://jovian.ai/lafirm/numpy-array-operations'